### ISSUE TITLE
rosnode - rgbd_hand_gesture_recognition.py - parameter

### ISSUE THREAD

**Issue by thomaspeyrucain** [opendr-eu/opendr#303]
Parameters need to be consistent with other tools with agparser

I am using opendr installed on my computer on the develop branch, I am feeding the rgb camera topic and the depth_image like this one:
![image](https://user-images.githubusercontent.com/87322480/189691815-70295f19-f66f-455e-ac79-eff6f0c78533.png)

I cannot get an output from the /opendr/gestures topic
Is the depth_image topic different from the one that you are using?

**Comment by minhquoc0712** [comment]
@thomaspeyrucain , I have created the branch named `ros1-fixed-rgbd-hand-gestures-recognition`. Can you try to run the corresponding ros node from this branch? Since currently I don't have any kinect device with me to test the fixed ros node.

**Comment by thomaspeyrucain** [comment]
Hello @minhquoc0712 ,
Sorry for the late reply, I saw that it is already merged in develop, I retried and I cannot succeed to get the output topic, maybe we can quickly meet next week to check it

**Comment by minhquoc0712** [comment]
Are you using the newest version of the node? Since after we merge the fix branch into `develop`, we also fix some bugs.

**Comment by thomaspeyrucain** [comment]
Yes

**Comment by minhquoc0712** [comment]
@thomaspeyrucain, can you try the node I just updated in this branch, and maybe modify the `delay` parameter if needed?

**Comment by thomaspeyrucain** [comment]
@minhquoc0712 Yes thanks now I get the output:
```
---
header: 
  seq: 351
  stamp: 
    secs: 1666088087
    nsecs: 507776260
  frame_id: ''
results: 
  - 
    id: 8
    score: 0.3937682509422302
source_img: 
  header: 
    seq: 0
    stamp: 
      secs: 0
      nsecs:         0
    frame_id: ''
  height: 0
  width: 0
  encoding: ''
  is_bigendian: 0
  step: 0
  data: []
---
```
I cannot find in the documentation what ID correspond what gesture
